feat(utility): implement class "MutableLazyList"
Graviti-AI/graviti-python-sdk pull request #104
Opened 2022-04-18 16:56 UTC by linjiX

2022-04-18 16:56 UTC, GravitiRob commented
Task linked: [CU-27rq6nt SDK 实现 MutableLazyList](https://app.clickup.com/t/27rq6nt)

2022-04-19 04:04 UTC, AChenQ requested changes

2022-04-19 04:04 UTC, AChenQ commented on graviti/utility/lazy.py
> +        page = pa.array(values, type=self._dtype)
We need to build an ExtensionArray when `self._dtype` is the instance of GravitiExtension

2022-04-19 04:17 UTC, AChenQ approved these changes

2022-04-19 06:45 UTC, merged