feat(client): add implementation about open_api__do
Graviti-AI/graviti-python-sdk pull request #13
Opened 2022-01-26 11:28 UTC by graczhual

2022-01-26 11:48 UTC, linjiX requested changes

2022-01-26 11:48 UTC, linjiX commented on graviti/client/request.py
>      """Send a request to the TensorBay Open API.
`OpenAPI` without space between `Open` and `API`
Do not use `tensorbay` anymore

2022-01-26 11:56 UTC, linjiX commented on graviti/client/request.py
>  logger = logging.getLogger(__name__)
`logger` seems useless

2022-01-26 12:47 UTC, linjiX approved these changes

2022-01-26 12:48 UTC, linjiX requested changes

2022-01-26 12:48 UTC, linjiX commented on graviti/utility/__init__.py
> +
Commit message:
- add quotes to `open_api_do`?
- add ".py" for "request"?

2022-01-27 02:58 UTC, AChenQ approved these changes

2022-01-27 03:55 UTC, linjiX approved these changes

2022-01-27 03:55 UTC, Lee-000 approved these changes

2022-01-27 03:56 UTC, linjiX commented on graviti/utility/request.py
> +from requests.models import Response
shall we add requests to `requirment.txt`?

2022-01-27 04:05 UTC, merged