feat(dataframe): design structure and interfaces of Pandas extensions
Graviti-AI/graviti-python-sdk pull request #14
Opened 2022-01-27 09:32 UTC by AChenQ

2022-01-27 10:04 UTC, linjiX requested changes

2022-01-27 10:04 UTC, linjiX commented on requirements.txt
> +pandas
the pandas minimal version is needed.

2022-01-28 07:01 UTC, linjiX requested changes

2022-01-28 07:01 UTC, linjiX commented on graviti/dataframe/pandas_extension.py
> +class GravitiDtype(ExtensionDtype):  # type: ignore[misc]
what mypy error is ignored here?

2022-01-28 12:24 UTC, graczhual requested changes

2022-01-28 12:24 UTC, graczhual commented on graviti/dataframe/pandas_extension.py
> +            scalars : Each element will be an instance of the scalar type for this
do not need space here. same error elsewhere.

2022-02-22 07:19 UTC, AChenQ commented
Don't use pandas extensions.

2022-02-22 07:19 UTC, closed without merging