chore: add "docs" framework related files
Graviti-AI/graviti-python-sdk pull request #15
Opened 2022-01-27 09:41 UTC by graczhual

2022-01-27 10:08 UTC, linjiX requested changes

2022-01-27 10:08 UTC, linjiX commented on docs/source/conf.py
> +project = "TensorBay"
Do not use "TensorBay"

2022-01-27 10:08 UTC, linjiX commented on build_docs.yaml
> +          pip install sphinx furo
`pip install -r requirements_docs.txt`?

2022-01-27 10:08 UTC, linjiX commented on .readthedocs.yaml
> +# Copyright 2021 Graviti. Licensed under MIT License.
2022

2022-01-27 10:09 UTC, linjiX requested changes

2022-01-27 10:09 UTC, linjiX commented on .readthedocs.yaml
> +---
Will it be better if the commit type is "docs"?

2022-01-28 03:44 UTC, linjiX requested changes

2022-01-28 03:44 UTC, linjiX commented on docs/source/conf.py
> +html_favicon = "images/favicon.svg"
this file does not exist, will it make the build failed?

2022-01-28 06:56 UTC, linjiX commented on docs/source/images/favicon.svg
> +<?xml version="1.0" encoding="UTF-8"?>
this icon seems useless

2022-01-28 07:28 UTC, linjiX requested changes

2022-01-28 07:28 UTC, linjiX commented on build_docs.yaml
> +            ${{ hashFiles('requirements.txt') }}
shall we add the hash of `requirements_docs.txt` here?

2022-01-28 08:30 UTC, AChenQ approved these changes

2022-01-29 03:57 UTC, linjiX approved these changes

2022-01-29 06:48 UTC, merged