feat(openapi): adapt OpenAPIv2 sheet
Graviti-AI/graviti-python-sdk pull request #150
Opened 2022-04-26 09:29 UTC by wangyuqing0424

2022-04-26 09:29 UTC, GravitiRob commented
Task linked: [CU-27k14q0 OpenAPIv2 对接 —— Sheet](https://app.clickup.com/t/27k14q0)

2022-04-26 09:44 UTC, graczhual requested changes

2022-04-26 09:44 UTC, graczhual commented on graviti/openapi/sheet.py
> +
commit message: adapt OpenAPIv2 about sheet

2022-04-26 09:44 UTC, graczhual commented on graviti/openapi/sheet.py
> +    *,
do not need * here and _get_sheet

2022-04-26 09:44 UTC, graczhual commented on graviti/openapi/sheet.py
> +
blank line

2022-04-26 09:44 UTC, graczhual commented on graviti/openapi/sheet.py
> +        params["schema_format"] = schema_format
params = {"schema_format": schema_format}

2022-04-26 09:44 UTC, graczhual commented on graviti/openapi/sheet.py
> +
`r`?

2022-04-26 09:47 UTC, linjiX requested changes

2022-04-26 09:47 UTC, linjiX commented on graviti/openapi/sheet.py
> +        }
the indentation is wrong here.

2022-04-26 09:47 UTC, linjiX commented on graviti/openapi/sheet.py
> +            "schema": '{
why the schema example is different with create_sheet?

2022-04-26 09:48 UTC, graczhual requested changes

2022-04-26 09:48 UTC, graczhual commented on graviti/openapi/sheet.py
> +        ...         \"shape\": [28, 28]}]}","arrow_schema": ""}"
schema is dict here

2022-04-26 09:48 UTC, graczhual commented on graviti/openapi/sheet.py
> +                "data_volume": 10000
do not add "data_volume" in List sheet(draft and commit)

2022-04-26 09:48 UTC, graczhual commented on graviti/openapi/sheet.py
> +            "schema": '{
change the schema

2022-04-27 02:47 UTC, graczhual requested changes

2022-04-27 02:47 UTC, graczhual commented on graviti/openapi/sheet.py
> +) -> Dict[str, str]:
None

2022-04-27 02:49 UTC, graczhual requested changes

2022-04-27 02:49 UTC, graczhual commented on graviti/openapi/sheet.py
> +        ...     "_arrow_schema": ""
_arrow_schema =

2022-04-27 02:54 UTC, graczhual requested changes

2022-04-27 02:54 UTC, graczhual commented on graviti/openapi/sheet.py
> +    schema: Dict[str, str],
string

2022-04-27 02:54 UTC, graczhual commented on graviti/openapi/sheet.py
> +        schema: The schema to be passed in.
The portex schema of the sheet.

2022-04-27 02:55 UTC, graczhual requested changes

2022-04-27 02:55 UTC, graczhual commented on graviti/openapi/sheet.py
> +        _arrow_schema: The arrow schema to be passed in.
The arrow schema of the sheet.

2022-04-27 03:19 UTC, graczhual requested changes

2022-04-27 03:19 UTC, graczhual commented on graviti/openapi/sheet.py
> +        ...     _arrow_schema: "The arrow schema of the sheet."
_arrow_schema = “”

2022-04-27 03:21 UTC, graczhual requested changes

2022-04-27 03:21 UTC, graczhual commented on graviti/openapi/sheet.py
> +        ... )
blank line

2022-04-27 03:23 UTC, graczhual requested changes

2022-04-27 03:23 UTC, graczhual commented on graviti/openapi/sheet.py
> +            schema is json or yaml. If None, it is to return json
None means "JSON" format. get_draft_sheet also need to modify

2022-04-27 03:33 UTC, graczhual commented on graviti/openapi/sheet.py
> +        }
blank line

2022-04-27 03:33 UTC, graczhual commented on graviti/openapi/sheet.py
> +        ...     _arrow_schema: ""
`=` not `:`

2022-04-27 03:36 UTC, graczhual requested changes

2022-04-27 03:36 UTC, graczhual commented on graviti/openapi/sheet.py
> +    ).json()
return None, do not use return

2022-04-27 03:36 UTC, graczhual commented on graviti/openapi/sheet.py
> +        The response of OpenAPI.
no Returns

2022-04-27 03:53 UTC, graczhual approved these changes

2022-04-27 03:54 UTC, linjiX approved these changes

2022-04-27 03:56 UTC, merged