feat(dataframe): implement "DataFrame.from_pyarrow"
Graviti-AI/graviti-python-sdk pull request #158
Opened 2022-04-27 16:45 UTC by AChenQ

2022-04-27 16:45 UTC, GravitiRob commented
Task linked: [CU-28v2czn 基于 PagingList 实现 DataFrame.__init__ 方法](https://app.clickup.com/t/28v2czn)

2022-04-27 17:18 UTC, linjiX requested changes

2022-04-28 08:32 UTC, AChenQ commented on graviti/dataframe/frame.py
> +                    column_value, schema=column_schema  # type:ignore[arg-type]
We only judge whether pyarrow type is `StructType`, so mypy does not know the schema type is `record`

2022-04-28 08:43 UTC, linjiX approved these changes

2022-04-28 09:08 UTC, Lee-000 approved these changes

2022-04-28 09:10 UTC, merged