feat(dataframe): implement "DataFrame.extend" and "column.Series.extend"
Graviti-AI/graviti-python-sdk pull request #168
Opened 2022-04-29 08:59 UTC by AChenQ

2022-04-29 08:59 UTC, GravitiRob commented
Task linked: [CU-28v2d3k 实现 DataFrame.extend 方法](https://app.clickup.com/t/28v2d3k)

2022-04-29 09:06 UTC, linjiX requested changes

2022-04-29 09:06 UTC, linjiX commented on graviti/dataframe/column/series.py
> +        raise NotImplementedError("Not support generating Series by __init__.")
seems unrelated with this commit?

2022-04-29 09:06 UTC, linjiX commented on graviti/dataframe/frame.py
> +            objs = self.__class__.from_pyarrow(pa.array(objs))
create pa.array with specific type.

2022-04-29 13:57 UTC, linjiX requested changes

2022-04-29 13:57 UTC, linjiX commented on graviti/dataframe/frame.py
> +        if not isinstance(objs, self.__class__):
`objs` looks like more than one instance.
maybe `objs` -> `values`?

2022-04-29 13:57 UTC, linjiX commented on graviti/dataframe/frame.py
> +            if self.schema != objs.schema:
Portex schema do not have `__eq__` method.
Also here checking the pyarrow type is enough

2022-05-01 15:42 UTC, linjiX requested changes

2022-05-01 15:42 UTC, linjiX commented on graviti/dataframe/frame.py
> +            values = self.__class__.from_pyarrow(pa.array(values, self.schema.to_pyarrow()))
`from_pyarrow` or `_from_pyarrow`?

2022-05-02 02:01 UTC, linjiX approved these changes

2022-05-02 02:52 UTC, linjiX requested changes

2022-05-02 02:52 UTC, linjiX commented on graviti/dataframe/frame.py
> +    def _extend(self, objs: "DataFrame") -> None:
`objs` -> `values`?

2022-05-02 02:56 UTC, linjiX approved these changes

2022-05-02 03:19 UTC, merged