feat(openapi): use "__record_key" to replace "order_by" and "offset"
Graviti-AI/graviti-python-sdk pull request #182
Opened 2022-05-02 13:34 UTC by graczhual

- Reduce the possibility of conflicts when multiple users modify the data
- It will be more convenient to expand the interface later.

2022-05-02 14:17 UTC, linjiX commented on graviti/openapi/data.py
> +    strategy_arguments: Optional[Dict[str, Any]] = None,
shall we rename the `primary_key_strategy` to `record_key_strategy`

2022-05-02 14:23 UTC, Lee-000 reviewed
I don't think your commit message matches your changes, which one is inaccurate?

2022-05-02 16:00 UTC, linjiX requested changes

2022-05-02 16:00 UTC, linjiX commented on graviti/openapi/data.py
> +            The rest are sorted by `__record_key` first.
should `__record_key` appear in commit message?

2022-05-02 16:22 UTC, Lee-000 commented on graviti/openapi/data.py
> +        order_by: The string of column names whose order determines the precedence of the sort.
Do we need to mention the column name separator here?

2022-05-03 02:04 UTC, linjiX approved these changes

2022-05-03 02:22 UTC, Lee-000 approved these changes

2022-05-03 02:22 UTC, merged