feat(dataset): design structure and interfaces of Dataset
Graviti-AI/graviti-python-sdk pull request #19
Opened 2022-02-24 10:18 UTC by graczhual

2022-02-24 12:05 UTC, linjiX requested changes

2022-02-24 12:12 UTC, linjiX requested changes

2022-02-24 12:12 UTC, linjiX commented on graviti/dataset/version.py
> +    def update_draft(
will it be better we move the draft related operation into `Draft` instance?
```python
draft = dataset.get_draft()
draft.update()
draft.close()
...
```

Also consider commit branch and tag?

2022-02-24 12:12 UTC, linjiX commented on graviti/dataset/version.py
> +    def checkout(self, revision: Optional[str] = None, draft_number: Optional[int] = None) -> None:
will it be better to separate `checkout` and `checkout_draft` as two methods?

2022-02-24 12:31 UTC, Lee-000 commented on graviti/dataset/graviti.py
> +        url: str = "",
Should `Graviti` have `access_key` and `url` properties?

2022-03-01 10:06 UTC, AChenQ approved these changes

2022-03-01 11:54 UTC, Lee-000 requested changes

2022-03-01 11:54 UTC, Lee-000 commented on graviti/dataset/dataset.py
> +        """Get class :class:`~graviti.manager.dataset.BranchManager`.
Get `class` or the `instance`?

2022-03-01 11:54 UTC, Lee-000 commented on graviti/dataset/dataset.py
> +        """Commit the draft.
`Commit the current draft` for better understanding?

2022-03-01 11:54 UTC, Lee-000 commented on graviti/dataset/manager.py
> +    """This class defines the operations on the dataset in Graviti.
`in Graviti` or `on Graviti`?

2022-03-01 11:54 UTC, Lee-000 commented on graviti/dataset/manager.py
> +                If the revision is not given, create the branch based on the current commit.
How to get the current commit?

2022-03-01 13:11 UTC, Lee-000 approved these changes

2022-03-01 13:12 UTC, linjiX approved these changes

2022-03-01 13:13 UTC, merged