feat(dataset): add implementation about class "Graviti"
Graviti-AI/graviti-python-sdk pull request #21
Opened 2022-03-02 08:05 UTC by graczhual

2022-03-02 09:54 UTC, linjiX requested changes

2022-03-02 09:54 UTC, linjiX commented on graviti/dataset/graviti.py
> +        return DatasetManager(self.access_key, self.url)
create `DatasetManager` in `datasets` property or in `__init__` method?

2022-03-02 10:08 UTC, linjiX approved these changes

2022-03-02 10:11 UTC, Lee-000 approved these changes

2022-03-02 11:38 UTC, AChenQ approved these changes

2022-03-02 11:41 UTC, merged

2022-03-04 08:08 UTC, GravitiRob commented
Task linked: [CU-2cct9y2 实现 Graviti 类，支持用户通过 AccessKey 登录](https://app.clickup.com/t/2cct9y2)