feat(manager): implement get & list methods for the class DatasetManager
Graviti-AI/graviti-python-sdk pull request #22
Opened 2022-03-02 09:01 UTC by graczhual

2022-03-02 09:59 UTC, linjiX requested changes

2022-03-02 09:59 UTC, linjiX commented on graviti/__init__.py
> +__all__ = ["DataFrame", "Series", "Graviti"]
should this line be moved to the `Graviti` implementation PR?

2022-03-03 06:16 UTC, GravitiRob commented
Task linked: [CU-2ccta0j 实现 DatasetManager 类中的 get 和 list 方法，支持用户管理数据集列表](https://app.clickup.com/t/2ccta0j)

2022-03-03 06:17 UTC, linjiX approved these changes

2022-03-03 06:51 UTC, Lee-000 approved these changes

2022-03-03 09:28 UTC, AChenQ approved these changes

2022-03-03 09:34 UTC, merged