fix(openapi): adapt to error response without "code" in content
Graviti-AI/graviti-python-sdk pull request #235
Opened 2022-05-13 03:09 UTC by Lee-000

When requesting to openAPI, there may be exceptions during transmission,
which leads to error response without "code" in content.

2022-05-13 03:25 UTC, linjiX requested changes

2022-05-13 03:25 UTC, linjiX commented on graviti/openapi/requests.py
> +        error_code = response.json().get("code", "InternalServerError")
shall we use a new Error code for status code `503`
Also, shall we also handle `404` error here?

2022-06-10 06:40 UTC, linjiX commented on graviti/exception.py
> +class NotFound(ResponseError):
shall we name this error as `NotFoundError`?

2022-06-10 06:52 UTC, linjiX approved these changes

2022-06-10 06:56 UTC, graczhual approved these changes

2022-06-10 06:59 UTC, merged