feat(portex): add check for enum values to fit Avro Enum type standard
Graviti-AI/graviti-python-sdk pull request #272
Opened 2022-05-24 13:38 UTC by Lee-000

2022-05-24 13:39 UTC, GravitiRob commented
Task linked: [CU-2da01j4 SDK portex enum values 添加 avro 规则检查，要求符合 [A-Za-z_][A-Za-z0-9_]* 正则表达式](https://app.clickup.com/t/2da01j4)

2022-05-25 02:33 UTC, linjiX requested changes

2022-05-25 02:33 UTC, linjiX commented on graviti/portex/ptype.py
> +        for value in arg:
shall we check whether the arg is List? Or shall we check the value is string first?

2022-05-25 03:05 UTC, linjiX approved these changes

2022-05-25 03:07 UTC, linjiX commented on graviti/portex/builtin.py
> -    values: List[Any] = param(ptype=PTYPE.Array)
shall we keep the PTYPE.Array?

2022-05-25 03:23 UTC, merged