feat(portex): add schema update in "DataFrame.__setitem__"
Graviti-AI/graviti-python-sdk pull request #273
Opened 2022-05-24 13:39 UTC by Lee-000

2022-05-24 13:39 UTC, GravitiRob commented
Task linked: [CU-28v2geg 支持追加列行为在 DataFrame 和 schema 之间的联动](https://app.clickup.com/t/28v2geg)

2022-06-20 09:04 UTC, AChenQ approved these changes

2022-06-20 09:24 UTC, linjiX requested changes

2022-06-20 09:24 UTC, linjiX commented on graviti/dataframe/frame.py
> +        self.schema[key] = schema
we need to add check for replace column

2022-06-20 10:19 UTC, linjiX requested changes

2022-06-20 10:19 UTC, linjiX commented on graviti/dataframe/frame.py
> +            raise NotImplementedError("Replacing a column is not supported yet")
do we need to mention the dataframe is a sheet in commit, not a local dataframe?

2022-06-20 10:20 UTC, linjiX requested changes

2022-06-20 10:20 UTC, linjiX commented on graviti/dataframe/frame.py
> +        if self.operations is not None and key in self._column_names:
we need the check operatinos and _colmun_names again, can we refiine it?

2022-06-20 11:23 UTC, linjiX requested changes

2022-06-20 11:41 UTC, merged