feat(dataframe): support column and row Series
Graviti-AI/graviti-python-sdk pull request #28
Opened 2022-03-04 09:24 UTC by AChenQ

2022-03-04 09:24 UTC, GravitiRob commented
Task linked: [CU-2b4rn1u 实现 Series 类，支持通过 index 和 integer-location 索引数据](https://app.clickup.com/t/2b4rn1u)

2022-03-06 07:57 UTC, linjiX requested changes

2022-03-06 07:57 UTC, linjiX commented on graviti/dataframe/column/series.py
> +    def _get_loc_by_index(self, key: Union[int, Iterable[int]]) -> Union[int, List[int]]:
shall we add overload for `_get_loc_by_index`?

2022-03-06 07:57 UTC, linjiX commented on graviti/dataframe/column/series.py
> +                return [index for index in key]  # pylint: disable=unnecessary-comprehension
`list(key)`?

2022-03-06 07:57 UTC, linjiX commented on graviti/dataframe/column/series.py
> +    def _get_loc_by_index(self, key: Union[int, Iterable[int]]) -> Union[int, List[int]]:
What is the difference between `loc` and `location`? why we have `loc` and `location` in function name?

2022-03-06 07:57 UTC, linjiX commented on graviti/dataframe/column/series.py
> +            index = [idx for idx in key]  # pylint: disable=unnecessary-comprehension
`list(key)`?

2022-03-06 08:02 UTC, linjiX requested changes

2022-03-06 08:02 UTC, linjiX commented on graviti/dataframe/column/series.py
> +            index = [idx for idx in key]  # pylint: disable=unnecessary-comprehension
`indices`?

2022-03-06 08:02 UTC, linjiX commented on graviti/dataframe/column/series.py
> +            index = [idx for idx in key]  # pylint: disable=unnecessary-comprehension
idx is abbreviation of index, it is weird idx and index appears at the same place

2022-03-07 06:39 UTC, linjiX requested changes

2022-03-07 06:39 UTC, linjiX commented on graviti/dataframe/column/series.py
> +        index: Optional[List[int]] = None,
should the index type be `Iterable`?

2022-03-07 08:52 UTC, Lee-000 requested changes

2022-03-07 08:52 UTC, Lee-000 commented on graviti/dataframe/column/series.py
> +    def _getitem_by_location(self, key: int) -> Union["Series", Any]:
In what case would the return type be of `Series`? If it does return a `Series`, should the schema not only be of a single dtype? And why the return type is different than `__getitem__`?

2022-03-07 08:52 UTC, Lee-000 commented on graviti/dataframe/row/series.py
> +        schema: Data type to force. Only a single dtype is allowed. If None, will be
Could `A single dtype` describe all the column types?

2022-03-07 10:59 UTC, graczhual approved these changes

2022-03-07 12:04 UTC, linjiX commented on graviti/dataframe/column/series.py
> +    def __init__(  # pylint: disable=too-many-arguments
we have only 5 arguments here, is this disable comments useless?

2022-03-07 12:05 UTC, linjiX commented on graviti/dataframe/column/series.py
> +"""The implementation of the Lazy Series."""
Why "Lazy"?

2022-03-07 12:19 UTC, linjiX approved these changes

2022-03-07 14:00 UTC, Lee-000 approved these changes

2022-03-07 14:08 UTC, merged