feat(schema): implement the Portex template type
Graviti-AI/graviti-python-sdk pull request #30
Opened 2022-03-07 13:56 UTC by linjiX

2022-03-07 13:56 UTC, GravitiRob commented
Task linked: [CU-2b4qrc5 实现 Portex 模板类型 python 表示](https://app.clickup.com/t/2b4qrc5)

2022-03-08 03:22 UTC, graczhual requested changes

2022-03-08 03:56 UTC, Lee-000 commented on graviti/schema/factory.py
> +        decl: A dict indicate a portex type.
`A dict which indicates ...`?

2022-03-08 06:28 UTC, graczhual commented on graviti/schema/base.py
> +        annotation: Any = _empty,
`annotation` needs to be added to `Arguments`

2022-03-08 09:31 UTC, Lee-000 commented on graviti/schema/factory.py
> +        decl: A dict indicate a dynamic Portex type.
Should the description in docstring be unified?

2022-03-08 09:31 UTC, Lee-000 commented on graviti/schema/factory.py
> +        A ``VariableFactory`` or a ``VariableFactory`` instance according to the input.
```
A ``VariableFactory`` or a ``ConstantFactory``
```

2022-03-08 11:37 UTC, graczhual approved these changes

2022-03-08 11:37 UTC, merged