feat(schema): design the format of mapping from field name to extractor
Graviti-AI/graviti-python-sdk pull request #31
Opened 2022-03-08 09:05 UTC by Lee-000

2022-03-08 09:06 UTC, GravitiRob commented
Task linked: [CU-2cy5uvx 确定 field name + type 到 extractor + dtype 映射的格式，并实现 filename 作为 example](https://app.clickup.com/t/2cy5uvx)

2022-03-08 11:18 UTC, linjiX requested changes

2022-03-08 11:18 UTC, linjiX commented on graviti/schema/get_extractor.py
> +#!/usr/bin/env python3
the file name should be a noun, may be `extractors.py` is better

2022-03-10 09:19 UTC, graczhual requested changes

2022-03-10 09:26 UTC, graczhual requested changes

2022-03-10 09:26 UTC, graczhual commented on graviti/schema/extractors.py
> +        ...     lazy_lists[key] = factory.create_list(extractor)
dtype in `create_list()`?

2022-03-10 11:37 UTC, linjiX approved these changes

2022-03-10 11:40 UTC, graczhual approved these changes

2022-03-10 11:40 UTC, merged