docs: add docs of "schema" in "sheet management" of chapter "FEATURES"
Graviti-AI/graviti-python-sdk pull request #312
Opened 2022-06-01 13:12 UTC by Lee-000

2022-06-01 13:12 UTC, GravitiRob commented
Task linked: [CU-2bgyr5k SDK 文档编写 —— Features > Sheet Management > Schema](https://app.clickup.com/t/2bgyr5k)

2022-06-02 02:14 UTC, graczhual requested changes

2022-06-02 02:14 UTC, graczhual commented on docs/source/features/sheet_management/schema.rst
> + schema
All titles should be capitalized.

2022-06-02 02:14 UTC, graczhual commented on docs/source/features/sheet_management/schema.rst
> +
this url is useless?

2022-06-02 02:14 UTC, graczhual commented on docs/source/features/sheet_management/schema.rst
> +
should we add a concrete example of how to use these primitive types, complex types?

2022-06-02 02:14 UTC, graczhual commented on docs/source/features/sheet_management/schema.rst
> +
do we need to introduce the methods of PortexType schema?

2022-06-09 02:32 UTC, graczhual commented on docs/source/features/sheet_management/schema.rst
> +The array type can be created by giving the item type and length.
here, length is not required. Should we move it into another sentence. like:
The array type can be created by giving the item type. param length can be specified to fix the length of array.

2022-06-09 02:32 UTC, graczhual commented on docs/source/features/sheet_management/schema.rst
> +The names and types can be accessed by `fields`, which acts like a dict whose key is the column name and the value is column type.
could use `` or ref to fields

2022-06-09 02:32 UTC, graczhual commented on docs/source/features/sheet_management/schema.rst
> +   record.fields
Format it, make it easier to read. And do we need to add a example for using dict to initialize pt.record here?

2022-06-09 02:32 UTC, graczhual commented on docs/source/features/sheet_management/schema.rst
> +Take `OpenBytes`_ as an example, which is used as the standard exteranl package by Graviti.
standard or OpenBytes?

2022-06-09 03:51 UTC, graczhual commented on docs/source/features/sheet_management/schema.rst
> +For better comprehension and operations, SDK provides methods to expand exteranl Portex type to builtin types.
exteranl or external?

2022-06-09 03:51 UTC, graczhual commented on docs/source/features/sheet_management/schema.rst
> +   builtin_type = box2d.to_builtin()
do we need to print `internal_type` and `builtin_type` here for better understand?

2022-06-09 03:51 UTC, graczhual commented on docs/source/features/sheet_management/schema.rst
> +   Tag or commit ID as revision is recommended.
tag commit or tag name commit ID

2022-06-09 03:51 UTC, graczhual commented on docs/source/features/sheet_management/schema.rst
> +Take `standard`_ as an example, which is used as the standard exteranl package by Graviti.
exteranl or external

2022-06-09 03:51 UTC, graczhual commented on docs/source/features/sheet_management/schema.rst
> +   record.fields
do we need to print the `record` and `record.fields` here for better understand? And the array, tensor before

2022-06-09 06:46 UTC, graczhual commented on docs/source/features/sheet_management/schema.rst
> +Graviti SDK provides classes to initialize Portex primitive types.
use `:` instead of `.` before example

2022-06-09 07:52 UTC, graczhual approved these changes

2022-06-09 08:16 UTC, AChenQ approved these changes

2022-06-09 08:22 UTC, merged