refactor(exception): separate local raised errors from ReponseError
Graviti-AI/graviti-python-sdk pull request #317
Opened 2022-06-02 04:00 UTC by Lee-000

2022-06-02 04:00 UTC, GravitiRob commented
Task linked: [CU-2bpma5x 清理请求异常中无用的逻辑](https://app.clickup.com/t/2bpma5x)

2022-06-02 04:09 UTC, graczhual approved these changes

2022-06-02 06:35 UTC, linjiX requested changes

2022-06-02 06:35 UTC, linjiX commented on graviti/exception.py
> +class InvalidResourceNameError(ManagerError):
`InvalidResourceNameError` -> `ResourceNameError`?

2022-06-02 06:35 UTC, linjiX commented on graviti/exception.py
> +        identification: Union[int, str, None] = None,
should `resource` and `identification` be required parameter?

2022-06-02 06:35 UTC, linjiX commented on graviti/exception.py
> +        identification: Union[int, str, None] = None,
Also we need to reconsider the variable name of these parameter

2022-06-02 06:35 UTC, linjiX commented on graviti/exception.py
> +class OperationForbiddenError(ManagerError):
The name `OperationForbiddenError` is not clear

2022-06-07 11:03 UTC, linjiX commented on graviti/exception.py
> +        return f"{super().__str__()}. Please create a draft first"
why the message is separated？

2022-06-07 11:37 UTC, linjiX approved these changes

2022-06-07 11:40 UTC, merged