docs: add an attention about dataset.HEAD to "Commit a Draft"
Graviti-AI/graviti-python-sdk pull request #325
Opened 2022-06-08 12:17 UTC by graczhual

2022-06-08 12:17 UTC, GravitiRob commented
Task linked: [CU-2fzzmvg 为 Draft.commit 方法添加详细文档说明 commit 可能导致 branch 不同步](https://app.clickup.com/t/2fzzmvg)

2022-06-09 02:14 UTC, Lee-000 requested changes

2022-06-09 02:14 UTC, Lee-000 commented on docs/source/features/version_control/draft.rst
> +   the dataset may be one commit behind the server. In addition, consider the concurrent operation
Only one commit behind？Could there be more commits behind?
`consider the concurrent operation`? Rephrase this for better understanding?

2022-06-09 02:14 UTC, Lee-000 commented on docs/source/features/version_control/draft.rst
> +   It is necessary to ``checkout`` the specified branch, commit or tag before proceeding to the
`checkout` or `checkout to`?

2022-06-09 02:35 UTC, graczhual commented on docs/source/features/version_control/draft.rst
> +   It is necessary to ``checkout`` the specified branch, commit or tag before proceeding to the
git use checkout

2022-06-09 03:01 UTC, Lee-000 approved these changes

2022-06-09 03:08 UTC, merged