feat(dataframe): implemented search related Series
Graviti-AI/graviti-python-sdk pull request #353
Opened 2022-06-15 00:40 UTC by AChenQ

2022-06-15 00:41 UTC, GravitiRob commented
Task linked: [CU-313b6uy 编写不同类型sql.Series，支持将所有操作转为运算公式](https://app.clickup.com/t/313b6uy)

2022-06-15 02:56 UTC, linjiX requested changes

2022-06-15 02:56 UTC, linjiX commented on graviti/dataframe/sql/container.py
> +class SearchContainer:
seems this class is useless?

2022-06-15 02:56 UTC, linjiX commented on graviti/dataframe/sql/series.py
> +        return BooleanSeries(expr, pt.boolean())
the type of BooleanSeries must be pt.boolean(), do we need to set type as a parameter?

2022-06-15 02:56 UTC, linjiX commented on graviti/dataframe/sql/series.py
> +            return cls(expr, left.schema)
we except `int + float = float`, but here `int + float = int`

2022-06-15 10:16 UTC, linjiX requested changes

2022-06-16 09:33 UTC, linjiX requested changes

2022-06-16 09:33 UTC, linjiX commented on graviti/dataframe/sql/scalar.py
> +class NumericalOperatorsMinxin(SearchContainer):
Arithmetic

2022-06-17 02:42 UTC, linjiX requested changes

2022-06-17 02:42 UTC, linjiX commented on graviti/dataframe/sql/frame.py
> +        if isinstance(field, pt.record):
`field` may not be a builtin type

2022-06-17 02:42 UTC, linjiX commented on graviti/dataframe/sql/frame.py
> +                return ArrayNumericScalar("$.", field, expr)
why `$.` here but `$` in other place?

2022-06-17 02:42 UTC, linjiX commented on graviti/dataframe/sql/frame.py
> +                return ArrayNumericScalar("$.", field, expr)
why `$.` here but `$` in other place?

2022-06-17 02:42 UTC, linjiX commented on graviti/dataframe/sql/scalar.py
> +    def check_type_for_right(left: "NumberScalar", right: SearchContainer) -> None:
shall we use `staticmethod` here? can it be a normal method?

2022-06-17 02:42 UTC, linjiX commented on graviti/dataframe/sql/scalar.py
> +    def check_type_for_right(left: "NumberScalar", right: SearchContainer) -> None:
shall we use `staticmethod` here? can it be a normal method?

2022-06-17 02:42 UTC, linjiX commented on graviti/dataframe/sql/scalar.py
> +            raise TypeError(f"Invalid operation between schema={left.schema} and {right.schema}")
the error message should contain the operation type

2022-06-17 02:42 UTC, linjiX commented on graviti/dataframe/sql/scalar.py
> +            raise TypeError(f"Invalid operation between schema={left.schema} and {right.schema}")
the error message should contain the operation type

2022-06-17 08:52 UTC, linjiX requested changes

2022-06-17 08:52 UTC, linjiX commented on graviti/dataframe/sql/scalar.py
> +class ComparisonOperatorsMinxin:
`Mixin`

2022-06-17 08:52 UTC, linjiX commented on graviti/dataframe/sql/scalar.py
> +    def check_type_for_other(self, other: SearchContainer, opt: str) -> None:
this method is been defined twice, and the code is the same.

2022-06-17 12:28 UTC, linjiX requested changes

2022-06-17 12:28 UTC, linjiX commented on graviti/portex/external.py
> +            self.search_container = self.internal_type.search_container
set `internal_type` as a variable

2022-06-17 12:35 UTC, linjiX requested changes

2022-06-17 12:35 UTC, linjiX commented on graviti/dataframe/sql/array.py
> +"""The implementation of the search DataFrame and Series."""
The docstring should be updated

2022-06-17 12:41 UTC, linjiX approved these changes

2022-06-17 14:30 UTC, Lee-000 commented on graviti/dataframe/sql/array.py
> +            The ArraySeries with the size expression.
`ArraySeries`?

2022-06-17 14:30 UTC, Lee-000 commented on graviti/dataframe/sql/array.py
> +        """Query the data of a ArraySeries with a lambda function.
`an ArraySeries`?

2022-06-17 14:33 UTC, Lee-000 approved these changes

2022-06-17 14:36 UTC, merged