feat: implement "query" and "apply" in "DataFrame"
Graviti-AI/graviti-python-sdk pull request #358
Opened 2022-06-15 13:21 UTC by linjiX

2022-06-15 13:21 UTC, GravitiRob commented
Task linked: [CU-30xbexf 编写 DataFrame.query() 支持与发送搜索请求到后端，并读取搜索后的数据](https://app.clickup.com/t/30xbexf)

2022-06-16 01:56 UTC, graczhual approved these changes

2022-06-17 01:27 UTC, AChenQ requested changes

2022-06-17 14:50 UTC, AChenQ approved these changes

2022-06-17 14:51 UTC, merged