feat: implement "__new__" method of class "Series" in "column/series.py"
Graviti-AI/graviti-python-sdk pull request #371
Opened 2022-06-17 14:01 UTC by graczhual

2022-06-17 14:14 UTC, linjiX requested changes

2022-06-17 14:14 UTC, linjiX commented on graviti/dataframe/column/series.py
> +    def _from_pyarrow(array: pa.Array, schema: pt.PortexType) -> Any:
why `_from_pyarrow` is `staticmethod` rather than `classmethod`, and why the return type is `Any`?

2022-06-20 07:00 UTC, AChenQ commented on graviti/dataframe/column/series.py
> +        if value.__class__.__name__ == "DataFrame":
use `container.__name__` ?

2022-06-20 07:47 UTC, linjiX approved these changes

2022-06-20 08:23 UTC, AChenQ approved these changes

2022-06-20 08:33 UTC, merged