refactor: remove PortexType.get_keys and add DataFrame.get_file_columns
Graviti-AI/graviti-python-sdk pull request #416
Opened 2022-06-29 03:26 UTC by Lee-000

2022-06-29 03:26 UTC, GravitiRob commented
Task linked: [CU-2h26fze SDK 移除 PortexType.get_keys 方法](https://app.clickup.com/t/2h26fze)

2022-06-29 03:27 UTC, graczhual approved these changes

2022-06-29 03:34 UTC, AChenQ commented on graviti/dataframe/frame.py
> +            if isinstance(column, DataFrame):
use `elif`?

2022-06-29 03:38 UTC, AChenQ approved these changes

2022-06-29 03:42 UTC, linjiX requested changes

2022-06-29 03:42 UTC, linjiX commented on graviti/portex/external.py
> -        if not self.container.has_keys:
shall we remove the `has_keys` of `Container`?

2022-06-30 02:38 UTC, linjiX approved these changes

2022-06-30 02:45 UTC, merged