feat(dataframe): support "__setitem__" for DataFrame loc and iloc
Graviti-AI/graviti-python-sdk pull request #424
Opened 2022-07-01 08:52 UTC by AChenQ

2022-07-01 08:52 UTC, GravitiRob commented
Task linked: [CU-28v2d5b 实现 DataFrame.loc.__setitem__ 方法](https://app.clickup.com/t/28v2d5b)

2022-07-01 09:50 UTC, linjiX requested changes

2022-07-01 09:50 UTC, linjiX commented on graviti/dataframe/frame.py
> +        for key, field in self.schema.items():
will it be better to iter columns rather than schema ?

2022-07-01 09:50 UTC, linjiX commented on graviti/dataframe/frame.py
> +    def _set_item(self, key: int, value: Any) -> None:
the method name is not good

2022-07-04 05:04 UTC, linjiX approved these changes

2022-07-04 05:25 UTC, merged