feat: support synchronizing operations of the Series to the DataFrame
Graviti-AI/graviti-python-sdk pull request #427
Opened 2022-07-04 06:45 UTC by graczhual

2022-07-04 06:45 UTC, GravitiRob commented
Task linked: [CU-2rbp7qj 支持将 DataFrame 成员的行操作同步回主 DataFrame](https://app.clickup.com/t/2rbp7qj)

2022-07-04 07:48 UTC, AChenQ requested changes

2022-07-04 07:48 UTC, AChenQ commented on graviti/dataframe/column/series.py
> +            record_key = [_record_key[i] for i in range(len(value) + 1)[key]]  # type: ignore[index]
How about
`[_record_key[i] for i in range(*key.indices(key.stop))`

2022-07-04 07:48 UTC, AChenQ commented on graviti/dataframe/container.py
> +        is_sheet: Whether the DataFrame to which the operations belongs is a sheet of the draft.
wrong docstring

2022-07-04 08:03 UTC, AChenQ commented on graviti/dataframe/column/series.py
> +    3 4
align

2022-07-07 07:58 UTC, linjiX approved these changes

2022-07-07 08:10 UTC, AChenQ approved these changes

2022-07-07 09:08 UTC, merged