refactor(portex): remove ptype.Field
Graviti-AI/graviti-python-sdk pull request #434
Opened 2022-07-11 04:09 UTC by Lee-000

2022-07-11 04:09 UTC, GravitiRob commented
Task linked: [CU-2mmp9rz SDK Portex 删除 ptype.Field, 并禁止相关行为](https://app.clickup.com/t/2mmp9rz)

2022-07-11 13:37 UTC, linjiX requested changes

2022-07-11 13:37 UTC, linjiX commented on graviti/portex/factory.py
> +                "Use dict unpack for entire record field is not allowed. "
object unpack or dict unpack?

2022-07-12 01:59 UTC, linjiX approved these changes

2022-07-12 03:13 UTC, merged