feat(manager): support getting and putting files stored in AZURE
Graviti-AI/graviti-python-sdk pull request #474
Opened 2022-07-21 13:11 UTC by graczhual

2022-07-21 13:11 UTC, GravitiRob commented
Task linked: [CU-2p29v6j 二进制文件读取对接: AZURE](https://app.clickup.com/t/2p29v6j)

2022-07-21 13:17 UTC, linjiX requested changes

2022-07-21 13:17 UTC, linjiX commented on graviti/manager/policy.py
> +_AZURE_RETRY_CODE = "AuthenticationFailed"
put the retry code into the class

2022-07-21 13:47 UTC, linjiX requested changes

2022-07-21 13:47 UTC, linjiX commented on graviti/manager/policy.py
> +    _OSS_RETRY_CODE = {"InvalidAccessKeyId", "AccessDenied"}
the `_OSS` prefix can be removed?

2022-07-22 01:59 UTC, linjiX approved these changes

2022-07-22 02:49 UTC, merged