feat(dataframe): support delete rows in DataFrame and ColumnSeries
Graviti-AI/graviti-python-sdk pull request #478
Opened 2022-07-25 07:00 UTC by AChenQ

2022-07-25 07:00 UTC, GravitiRob commented
Task linked: [CU-2bpm5uq [parent] SDK 实现 Sheet 删除行的功能](https://app.clickup.com/t/2bpm5uq)

2022-07-25 08:22 UTC, linjiX requested changes

2022-07-25 08:22 UTC, linjiX commented on graviti/dataframe/column/indexing.py
> +        key: Union[int, slice],
remove the tailing comma?

2022-07-25 08:22 UTC, linjiX commented on graviti/dataframe/column/indexing.py
> +        key: Union[int, slice],
`key` or `index`?

2022-07-25 11:58 UTC, linjiX approved these changes

2022-07-26 02:14 UTC, linjiX requested changes

2022-07-26 02:14 UTC, linjiX commented on graviti/dataframe/column/indexing.py
> +    def __delitem__(self, key: Union[int, slice]) -> None:
support doing sth

2022-07-26 02:45 UTC, linjiX commented on graviti/dataframe/column/indexing.py
> +    def __delitem__(self, key: Union[int, slice]) -> None:
in commit message, the "series" and "row" are mismatched?

2022-07-26 02:56 UTC, linjiX approved these changes

2022-07-26 03:03 UTC, merged