feat(manager): implement "commit" method in class "Dataset"
Graviti-AI/graviti-python-sdk pull request #479
Opened 2022-07-25 08:57 UTC by graczhual

2022-07-25 08:57 UTC, GravitiRob commented
Task linked: [CU-2pz17n5 Dataset实现commit方法](https://app.clickup.com/t/2pz17n5)

2022-07-25 10:00 UTC, linjiX requested changes

2022-07-25 10:01 UTC, linjiX requested changes

2022-07-25 10:01 UTC, linjiX commented on graviti/manager/sheets.py
> +from tqdm import tqdm
`tqdm.auto`?

2022-07-26 02:14 UTC, linjiX commented on graviti/manager/dataset.py
> +        draft.operations = self.HEAD.operations
`head.operation`?

2022-07-26 02:25 UTC, linjiX requested changes

2022-07-26 02:25 UTC, linjiX commented on graviti/manager/dataset.py
> +        draft.operations = head.operations
does this line make sense?

2022-07-26 02:25 UTC, linjiX commented on graviti/manager/dataset.py
> +            title, description, branch=head.name  # type: ignore[attr-defined]
what if the head is not a branch?

2022-07-26 03:44 UTC, linjiX commented on graviti/manager/dataset.py
> +            StatusError: When the HEAD of the dataset is a COMMIT or a TAG.
`is commit or tag` or `not branch` which one is better?

2022-07-26 04:13 UTC, linjiX approved these changes

2022-07-26 04:14 UTC, linjiX commented on graviti/manager/dataset.py
> +            raise StatusError("It is not allowed to commit a dataset without any modifications")
better to add a blank line after raise

2022-07-26 04:38 UTC, merged