feat: support getting and putting files stored in S3
Graviti-AI/graviti-python-sdk pull request #483
Opened 2022-07-26 10:29 UTC by graczhual

2022-07-26 10:29 UTC, GravitiRob commented
Task linked: [CU-2p29v2p 二进制文件读取对接: S3](https://app.clickup.com/t/2p29v2p)

2022-07-26 10:47 UTC, linjiX commented on graviti/manager/policy.py
> +    _PUT_HASHED_PAYLOAD = "UNSIGNED-PAYLOAD"
the hashed payload is bound with verb, maybe we can use a dict to store them?

2022-07-26 10:48 UTC, linjiX commented on graviti/manager/__init__.py
> +    S3ObjectPolicyManager,
will it be better to set the commit scope to `manager`

2022-07-26 12:12 UTC, linjiX requested changes

2022-07-26 12:12 UTC, linjiX commented on graviti/manager/policy.py
> +        "GET": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
this string is meaningless for human, maybe the old presentation is better.

2022-07-26 12:12 UTC, linjiX commented on graviti/manager/policy.py
> +            f"x-amz-content-sha256:{hashed_payload}\n"
shall we also get the `hashed_payload` from the `dict` here?

2022-07-26 16:57 UTC, linjiX approved these changes

2022-07-27 00:30 UTC, merged

2022-07-27 00:34 UTC, GravitiRob commented
Task linked: [CU-2p29v0w 二进制文件上传对接: S3](https://app.clickup.com/t/2p29v0w)