feat(dataframe): add Dataset ObjectPolicyManager to Container
Graviti-AI/graviti-python-sdk pull request #493
Opened 2022-08-04 02:19 UTC by graczhual

2022-08-04 02:19 UTC, GravitiRob commented
Task linked: [CU-2p2hdk4 Container 增加 ObjectPolicy 实例](https://app.clickup.com/t/2p2hdk4)

2022-08-04 02:20 UTC, linjiX requested changes

2022-08-04 02:20 UTC, linjiX commented on graviti/dataframe/container.py
> +        object_policy_manager: Optional["ObjectPolicyManager"] = None,
will it be better to access the policy manager from `root`?

2022-08-05 07:54 UTC, linjiX approved these changes

2022-08-05 07:55 UTC, merged