feat(manager): add logs to the method "Dataset.commit"
Graviti-AI/graviti-python-sdk pull request #527
Opened 2022-08-30 09:13 UTC by graczhual

2022-08-30 09:13 UTC, GravitiRob commented
Task linked: [CU-2pz43c5 Dataset.commit 方法增加详细的 log](https://app.clickup.com/t/2pz43c5)

2022-08-30 14:16 UTC, linjiX requested changes

2022-08-31 02:43 UTC, linjiX commented on graviti/manager/dataset.py
> +        logger.info('Draft("#%d: %s") committed successfully', draft.number, draft.title)
will it be better to print the new commit info here?

2022-08-31 11:12 UTC, linjiX requested changes

2022-08-31 11:12 UTC, linjiX commented on graviti/manager/dataset.py
> +        logger.info("The HEAD of the dataset after commit: \n%s", branch.__repr__())
use `branch` to replace `branch.__repr__()`

2022-08-31 13:41 UTC, linjiX approved these changes

2022-08-31 13:52 UTC, merged