docs: add the description about the method "Dataset.commit"
Graviti-AI/graviti-python-sdk pull request #528
Opened 2022-08-30 14:03 UTC by graczhual

2022-08-30 14:03 UTC, GravitiRob commented
Task linked: [CU-2pz17ph 文档中增加简单上传/修改的描述](https://app.clickup.com/t/2pz17ph)

2022-08-31 11:15 UTC, linjiX requested changes

2022-08-31 11:15 UTC, linjiX commented on docs/source/getting_started/upload_dataset.rst
> +   dataset = ws.datasets.create("Graviti-dataset-demo")
the title is `create or get`, but the sample code only describe `create`, will it be better to add `get` in the sample code?

2022-08-31 11:15 UTC, linjiX commented on docs/source/getting_started/upload_dataset.rst
> +   dataframe = DataFrame(data=data, schema=schema)
use `df`?

2022-08-31 11:15 UTC, linjiX commented on docs/source/getting_started/upload_dataset.rst
> + Upload DataFrame
do we need to mention `commit` in the title?

2022-08-31 11:17 UTC, linjiX requested changes

2022-08-31 11:17 UTC, linjiX commented on docs/source/getting_started/upload_dataset.rst
> +SDK provides a simplified way to upload and modify data:
I think is not simplified way, it should be normal way, and using draft is complex way.

2022-08-31 13:46 UTC, linjiX commented on docs/source/getting_started/upload_dataset.rst
> +           "image": Image("PATH/TO/YOUR/IMAGE"),
will it be better to make the filename appear in the image path?

2022-08-31 13:53 UTC, linjiX approved these changes

2022-08-31 13:54 UTC, merged