build: add setup.py and setup.cfg
Graviti-AI/graviti-python-sdk pull request #68
Opened 2022-03-25 03:07 UTC by Lee-000

2022-03-25 03:07 UTC, GravitiRob commented
Task linked: [CU-2e0cx1x 提交打包配置文件 setup.py 与 setup.cfg](https://app.clickup.com/t/2e0cx1x)

2022-03-25 03:52 UTC, linjiX requested changes

2022-03-25 03:52 UTC, linjiX commented on setup.cfg
> +install_requires =
requires here should be the same as "requirements.txt"

2022-03-25 03:52 UTC, linjiX commented on setup.cfg
> +    Programming Language :: Python :: 3.10
Will it be better to remove 3.10 support until all features are tested in 3.10?

2022-03-26 13:18 UTC, linjiX requested changes

2022-03-26 13:18 UTC, linjiX commented on setup.cfg
> +    numpy >= 1.16.0; python_version < '3.7'
The numpy requirement is different with requirments.txt?

2022-03-28 06:43 UTC, linjiX approved these changes

2022-03-28 06:46 UTC, merged