refactor(utility): use pa.array instead of np.array in LazyList
Graviti-AI/graviti-python-sdk pull request #77
Opened 2022-03-31 11:39 UTC by AChenQ

2022-03-31 11:39 UTC, GravitiRob commented
Task linked: [CU-2hd6fr1 直接使用 pa.array 替换 numpy.array](https://app.clickup.com/t/2hd6fr1)

2022-03-31 12:55 UTC, Lee-000 requested changes

2022-03-31 12:55 UTC, Lee-000 commented on graviti/utility/lazy.py
> +        self, extractor: Callable[[Any], Iterable[Any]], dtype: pa.DataType
The docstring needs to be updated.
Also, do we still need the dtype?

2022-03-31 12:55 UTC, Lee-000 commented on graviti/utility/lazy.py
> +    def __getitem__(self, index: Union[int, slice]) -> Union[_T, pa.list_]:
Why the return type is `pa.list_`?

2022-03-31 12:55 UTC, Lee-000 commented on graviti/schema/extractors.py
>      return extractor, "object"
The return dtype is still `object`, is this acceptable?

2022-03-31 12:55 UTC, Lee-000 commented on graviti/schema/extractors.py
>  _PORTEX_TYPE_TO_NUMPY_DTYPE = {
Should the name be updated?

2022-04-01 03:03 UTC, Lee-000 requested changes

2022-04-01 03:03 UTC, Lee-000 commented on graviti/schema/extractors.py
> +                "vertices": [list(_extract_vetices(label[key], ("x", "y"))) for label in labels]
Is it ok to use `list` to convert the values of the dict here?

2022-04-01 06:51 UTC, Lee-000 approved these changes

2022-04-01 06:52 UTC, linjiX approved these changes

2022-04-01 06:56 UTC, merged