feat(utility): migrate user.py code
Graviti-AI/graviti-python-sdk pull request #83
Opened 2022-04-07 10:17 UTC by wangyuqing0424

2022-04-07 10:17 UTC, GravitiRob commented
Task linked: [CU-2jn2tvx TensorBay 代码迁移：utility/user.py](https://app.clickup.com/t/2jn2tvx)

2022-04-15 02:50 UTC, Lee-000 requested changes

2022-04-15 02:50 UTC, Lee-000 commented on graviti/utility/user.py
> +# Copyright 2021 Graviti. Licensed under MIT License.
Should the year be updated?

2022-04-15 02:55 UTC, Lee-000 approved these changes

2022-04-15 02:57 UTC, linjiX approved these changes

2022-04-15 02:58 UTC, merged