feat(openapi): adapt graviti OpenAPI about branch
Graviti-AI/graviti-python-sdk pull request #88
Opened 2022-04-12 03:42 UTC by willandfree

2022-04-12 03:42 UTC, GravitiRob commented
Task linked: [CU-2j40yd7 OpenAPIv2 对接 —— Branch](https://app.clickup.com/t/2j40yd7)

2022-04-12 03:45 UTC, graczhual requested changes

2022-04-12 03:45 UTC, graczhual commented on graviti/openapi/branch.py
> +#!/usr/bin/env python3
modify __init__, add this functions

2022-04-12 04:33 UTC, graczhual requested changes

2022-04-12 04:33 UTC, graczhual commented on graviti/openapi/branch.py
> +
blank line

2022-04-12 13:13 UTC, graczhual requested changes

2022-04-12 13:13 UTC, graczhual commented on graviti/openapi/branch.py
> +    params: Dict[str, Any] = {"offset": offset, "limit": limit}
Dict[str, int]

2022-04-12 13:13 UTC, graczhual commented on graviti/openapi/branch.py
> +    """Execute the OpenAPI `GET /v1/datasets/{dataset_name}/branches`.
`GET /v1/datasets/{dataset_name}/branches/{branch_name}`

2022-04-12 13:13 UTC, graczhual commented on graviti/openapi/branch.py
> +    *,
do not need * here

2022-04-12 13:22 UTC, graczhual commented on graviti/openapi/branch.py
> +    params: Dict[str, Any] = {"offset": offset, "limit": limit}
do not need to add typing here

2022-04-13 05:02 UTC, graczhual approved these changes

2022-04-14 02:18 UTC, graczhual approved these changes

2022-04-14 03:12 UTC, merged