feat(openapi): adapt graviti OpenAPI about draft
Graviti-AI/graviti-python-sdk pull request #89
Opened 2022-04-12 04:10 UTC by willandfree

2022-04-12 04:10 UTC, GravitiRob commented
Task linked: [CU-2j40ydf OpenAPIv2 对接 —— Draft](https://app.clickup.com/t/2j40ydf)

2022-04-12 04:23 UTC, graczhual requested changes

2022-04-12 04:23 UTC, graczhual commented on graviti/openapi/draft.py
> +#!/usr/bin/env python3
add these functions to `__init__`

2022-04-12 06:33 UTC, linjiX commented on graviti/openapi/draft.py
> +    post_data = {"branchName": branch_name, "title": title}
should the naming style be snake_case?
branchName -> branch_name

2022-04-12 13:29 UTC, graczhual requested changes

2022-04-12 13:29 UTC, graczhual commented on graviti/openapi/draft.py
> +def get_draft(url: str, access_key: str, dataset_name: str, *, draft_number: int) -> Dict[str, Any]:
do not need to add * here

2022-04-12 13:29 UTC, graczhual commented on graviti/openapi/draft.py
> +        patch_data["status"] = state
state

2022-04-12 13:29 UTC, graczhual commented on graviti/openapi/draft.py
> +        ...     status="CLOSED"
state

2022-04-12 13:29 UTC, graczhual commented on graviti/openapi/draft.py
> +    """Execute the OpenAPI `DELETE /v1/datasets/{dataset_name}/drafts/{draft_number}`.
Deleting drafts should not be supported. There's a mistake in the documentation.

2022-04-14 02:19 UTC, graczhual requested changes

2022-04-14 02:19 UTC, graczhual commented on graviti/openapi/draft.py
> +    branch_name: str,
branch_name is not required.

2022-04-14 03:17 UTC, graczhual requested changes

2022-04-14 03:17 UTC, graczhual commented on graviti/openapi/draft.py
> +    branch_name: Optional[str] = None,
use * before branch_name

2022-04-14 03:17 UTC, graczhual commented on graviti/openapi/draft.py
> +        post_data["description"] = description
if branch_name

2022-04-14 04:09 UTC, graczhual requested changes

2022-04-14 04:09 UTC, graczhual commented on graviti/openapi/draft.py
> +        ...     "main",
branch_name=

2022-04-14 04:09 UTC, graczhual commented on graviti/openapi/draft.py
> +
do not need blank line

2022-04-14 04:09 UTC, graczhual commented on graviti/openapi/draft.py
> +        branch_name: The branch name.
Add an explanation of what None means. like the state in list drafts

2022-04-14 04:09 UTC, graczhual commented on graviti/openapi/draft.py
> +            where None means listing open drafts.
do not need where

2022-04-14 08:16 UTC, graczhual requested changes

2022-04-14 08:16 UTC, graczhual commented on graviti/openapi/draft.py
> +            None means the default branch of the dataset.
do not need another line

2022-04-14 11:21 UTC, graczhual approved these changes

2022-04-14 11:21 UTC, linjiX approved these changes

2022-04-14 11:29 UTC, merged