feat(dataset): add class "Commit" to support basic version control
Graviti-AI/graviti-python-sdk pull request #93
Opened 2022-04-13 03:17 UTC by graczhual

2022-04-13 03:17 UTC, GravitiRob commented
Task linked: [CU-2k67ayq 版本管理基础类：Commit](https://app.clickup.com/t/2k67ayq)

2022-04-13 03:51 UTC, linjiX requested changes

2022-04-13 03:51 UTC, linjiX commented on graviti/dataset/struct.py
> +    parent_commit_id: Optional[str] = attr(key=camel)
do we still need `key=camel`?

2022-04-13 03:51 UTC, linjiX commented on graviti/dataset/struct.py
> +    def loads(cls: Type[_T], contents: Dict[str, Any]) -> _T:
we do not use `loads` and `dumps` in graviti SDK
use `from_xxx`, `to_xxx` instead

2022-04-13 03:51 UTC, linjiX commented on graviti/dataset/struct.py
> +                    "parentCommitId": <str> or None
`parent_commit_id`?

2022-04-14 03:30 UTC, linjiX commented on graviti/dataset/struct.py
> +    parent_commit_id: str = attr(default="")
should the `parent_commit_id` default to `""`

2022-04-14 04:18 UTC, linjiX commented on graviti/dataset/struct.py
> +    parent_commit_id: str = attr(default="")
@Lee-000 please help on this

2022-04-14 07:50 UTC, linjiX approved these changes

2022-04-14 10:31 UTC, merged